# Generated by Django 4.0.5 on 2024-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.TextField(choices=[('vfx', 'VFX'), ('btc', 'BTC')], max_length=6)),
                ('usdt_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('volume_24h', models.DecimalField(decimal_places=4, max_digits=8)),
                ('percent_change_1h', models.DecimalField(decimal_places=4, max_digits=8)),
                ('percent_change_24h', models.DecimalField(decimal_places=4, max_digits=8)),
                ('percent_change_7d', models.DecimalField(decimal_places=4, max_digits=8)),
                ('percent_change_30d', models.DecimalField(decimal_places=4, max_digits=8)),
                ('percent_change_60d', models.DecimalField(decimal_places=4, max_digits=8)),
                ('percent_change_90d', models.DecimalField(decimal_places=4, max_digits=8)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'unique_together': {('coin_type', 'last_updated')},
            },
        ),
    ]
