# Generated by Django 4.0.5 on 2024-09-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprice',
            name='percent_change_1h',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='percent_change_24h',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='percent_change_30d',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='percent_change_60d',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='percent_change_7d',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='percent_change_90d',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='usdt_price',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='volume_24h',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
    ]
