# Generated by Django 4.0.5 on 2024-11-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_coinprice_percent_change_1h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinprice',
            name='percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='coinprice',
            name='percent_change_30d',
        ),
        migrations.RemoveField(
            model_name='coinprice',
            name='percent_change_60d',
        ),
        migrations.RemoveField(
            model_name='coinprice',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='coinprice',
            name='percent_change_90d',
        ),
    ]
