# Generated by Django 4.0.5 on 2022-07-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.IntegerField(primary_key=True, serialize=False, verbose_name='Height')),
                ('hash', models.CharField(max_length=255, verbose_name='Hash')),
                ('previous_hash', models.CharField(max_length=255, verbose_name='Previous Hash')),
                ('validator_address', models.CharField(max_length=255, verbose_name='Validator Address')),
                ('validator_signature', models.CharField(max_length=255, verbose_name='Validator Signature')),
                ('validator_answer', models.CharField(max_length=255, verbose_name='Validator Answer')),
                ('chain_ref_id', models.CharField(max_length=255, verbose_name='Chain Reference ID')),
                ('merkle_root', models.CharField(max_length=255, verbose_name='Merkle Root')),
                ('state_root', models.CharField(max_length=255, verbose_name='State Root')),
                ('total_reward', models.DecimalField(decimal_places=16, default=0.0, max_digits=32, verbose_name='Total Reward')),
                ('total_amount', models.DecimalField(decimal_places=16, default=0.0, max_digits=32, verbose_name='Total Amount')),
                ('total_validators', models.IntegerField(default=0, verbose_name='Total Validators')),
                ('version', models.IntegerField(default=0, verbose_name='Version')),
                ('size', models.IntegerField(default=0, verbose_name='Size')),
                ('craft_time', models.IntegerField(default=0, verbose_name='Craft Time')),
                ('date_crafted', models.DateTimeField(verbose_name='Date Crafted')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['-height'],
            },
        ),
        migrations.CreateModel(
            name='MasterNode',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Address')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('connection_id', models.TextField(blank=True, verbose_name='Connection ID')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP Address')),
                ('wallet_version', models.CharField(max_length=255, verbose_name='Wallet Version')),
                ('date_connected', models.DateTimeField(verbose_name='Date Connected')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('time_zone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Time Zone')),
                ('latitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=32, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=32, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Master Node',
                'verbose_name_plural': 'Master Nodes',
                'ordering': ['-date_connected'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Hash')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('type', models.IntegerField(choices=[(0, 'Tx'), (1, 'Node'), (2, 'Nft Mint'), (3, 'Nft Tx'), (4, 'Nft Burn'), (5, 'Nft Sale'), (6, 'Address'), (7, 'Dst Registration')], verbose_name='Type')),
                ('to_address', models.CharField(max_length=255, verbose_name='To Address')),
                ('from_address', models.CharField(max_length=255, verbose_name='From Address')),
                ('total_amount', models.DecimalField(decimal_places=16, default=0.0, max_digits=32, verbose_name='Total Amount')),
                ('total_fee', models.DecimalField(decimal_places=16, default=0.0, max_digits=32, verbose_name='Total Fee')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Validator Signature')),
                ('date_crafted', models.DateTimeField(verbose_name='Date Crafted')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='rbx.block', verbose_name='Block')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_crafted'],
            },
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('identifier', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('minter_address', models.CharField(max_length=64)),
                ('owner_address', models.CharField(max_length=64)),
                ('minter_name', models.CharField(max_length=255)),
                ('primary_asset_name', models.CharField(max_length=255)),
                ('primary_asset_size', models.PositiveIntegerField()),
                ('data', models.TextField()),
                ('smart_contract_data', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('minted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mint_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mint_transaction', to='rbx.transaction')),
                ('sale_transactions', models.ManyToManyField(blank=True, related_name='sale_transactions', to='rbx.transaction')),
                ('transfer_transactions', models.ManyToManyField(blank=True, related_name='transfer_transactions', to='rbx.transaction')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': 'NFTs',
                'ordering': ['minted_at'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='master_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocks', to='rbx.masternode', verbose_name='Master Node'),
        ),
    ]
