# Generated by Django 4.0.5 on 2022-07-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbx.nft'),
        ),
    ]
