# Generated by Django 4.0.5 on 2022-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0004_circulation_fees_burned_circulation_fees_burned_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='total_staked',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
    ]
