# Generated by Django 4.0.5 on 2022-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0006_nft_burn_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={'ordering': ['-minted_at'], 'verbose_name': 'NFT', 'verbose_name_plural': 'NFTs'},
        ),
        migrations.AddField(
            model_name='circulation',
            name='active_master_nodes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circulation',
            name='total_master_nodes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
