# Generated by Django 4.0.5 on 2022-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0008_tempaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternode',
            name='block_count',
            field=models.IntegerField(default=0),
        ),
    ]
