# Generated by Django 4.0.5 on 2022-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0009_masternode_block_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='lifetime_supply',
            field=models.DecimalField(decimal_places=16, default=372000000, max_digits=32),
        ),
    ]
