# Generated by Django 4.0.5 on 2022-12-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0011_sentmasternode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_address', models.CharField(max_length=64)),
                ('owner_signature', models.TextField(blank=True, null=True)),
                ('adjudicator_address', models.CharField(max_length=64)),
                ('block_height', models.PositiveIntegerField()),
                ('validator_count', models.PositiveIntegerField()),
                ('adjudicator_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('voter_type', models.IntegerField()),
                ('category', models.IntegerField()),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('percent_votes_yes', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('percent_votes_no', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('percent_in_favor', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('percent_against', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-created_at'],
            },
        ),
    ]
