# Generated by Django 4.0.5 on 2022-12-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0012_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-block_height'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='topic',
            name='votes_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='votes_yes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
