# Generated by Django 4.0.5 on 2022-12-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0013_alter_topic_options_topic_votes_no_topic_votes_yes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='adjudicator_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
