# Generated by Django 4.0.5 on 2023-01-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0014_alter_topic_adjudicator_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmasternode',
            name='date_connected',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date Connected'),
        ),
        migrations.AlterField(
            model_name='sentmasternode',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='sentmasternode',
            name='last_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Answer Connected'),
        ),
        migrations.AlterField(
            model_name='sentmasternode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sentmasternode',
            name='wallet_version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet Version'),
        ),
    ]
