# Generated by Django 4.0.5 on 2023-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0015_alter_sentmasternode_date_connected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masternode',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='masternode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='masternode',
            name='wallet_version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet Version'),
        ),
    ]
