# Generated by Django 4.0.5 on 2023-01-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0016_alter_masternode_ip_address_alter_masternode_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
                ('create_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adnr_creates', to='rbx.transaction')),
                ('delete_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adnr_deletes', to='rbx.transaction')),
                ('transfer_transactions', models.ManyToManyField(blank=True, related_name='adnr_transfers', to='rbx.transaction')),
            ],
        ),
    ]
