# Generated by Django 4.0.5 on 2023-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0019_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
