# Generated by Django 4.0.5 on 2023-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0020_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('block_difference_average', models.DecimalField(decimal_places=4, max_digits=8)),
                ('block_last_received', models.DateTimeField()),
                ('block_last_delay', models.IntegerField()),
                ('time_since_last_block', models.IntegerField()),
                ('blocks_averages', models.CharField(max_length=16)),
            ],
        ),
    ]
