# Generated by Django 4.0.5 on 2023-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0021_networkmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmetrics',
            name='block_difference_average',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='networkmetrics',
            name='block_last_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkmetrics',
            name='block_last_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkmetrics',
            name='blocks_averages',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='networkmetrics',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkmetrics',
            name='time_since_last_block',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
