# Generated by Django 4.0.5 on 2023-02-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0022_alter_networkmetrics_block_difference_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='block',
            name='validator_address',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Validator Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_address',
            field=models.CharField(db_index=True, max_length=255, verbose_name='From Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(db_index=True, max_length=255, verbose_name='To Address'),
        ),
    ]
