# Generated by Django 4.0.5 on 2023-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbx", "0023_alter_block_hash_alter_block_height_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="circulation",
        #     name="total_addresses",
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AlterField(
        #     model_name="address",
        #     name="address",
        #     field=models.CharField(
        #         db_index=True, max_length=36, primary_key=True, serialize=False
        #     ),
        # ),
    ]
