# Generated by Django 4.0.5 on 2023-04-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0026_alter_transaction_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='misc_transactions',
            field=models.ManyToManyField(blank=True, related_name='misc_transactions', to='rbx.transaction'),
        ),
    ]
