# Generated by Django 4.0.5 on 2023-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0024_circulation_total_addresses_alter_address_address'),
        ('rbx', '0027_nft_misc_transactions'),
    ]

    operations = [
    ]
