# Generated by Django 4.0.5 on 2023-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0028_merge_20230420_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='asset_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='on_chain',
            field=models.BooleanField(default=True),
        ),
    ]
