# Generated by Django 4.0.5 on 2023-04-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0029_nft_asset_urls_nft_on_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='mint_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mint_transaction', to='rbx.transaction'),
        ),
    ]
