# Generated by Django 4.0.5 on 2023-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0030_alter_nft_mint_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmasternode',
            name='address',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, verbose_name='Address'),
        ),
    ]
