# Generated by Django 4.0.5 on 2023-06-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0031_alter_sentmasternode_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unlock_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unlock Time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Tx'), (1, 'Node'), (2, 'Nft Mint'), (3, 'Nft Tx'), (4, 'Nft Burn'), (5, 'Nft Sale'), (6, 'Address'), (7, 'Dst Registration'), (8, 'Vote Topic'), (9, 'Vote'), (10, 'Reserve')], verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ReserveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=64)),
                ('from_address', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('settlement_datetime', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.transaction')),
            ],
        ),
    ]
