# Generated by Django 4.0.5 on 2023-06-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0032_transaction_unlock_time_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=64)),
                ('from_address', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_callbacks', to='rbx.transaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='rbx.transaction')),
            ],
        ),
    ]
