# Generated by Django 4.0.5 on 2023-06-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0033_callback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReserveTransaction',
        ),
    ]
