# Generated by Django 4.0.5 on 2023-06-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0034_delete_reservetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.CharField(max_length=64)),
                ('new_address', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='rbx.transaction')),
            ],
        ),
    ]
