# Generated by Django 4.0.5 on 2023-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0036_callback_from_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='voided_from_callback',
            field=models.BooleanField(default=False),
        ),
    ]
