# Generated by Django 4.0.5 on 2023-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0037_transaction_voided_from_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='outstanding_transactions',
            field=models.ManyToManyField(related_name='recovery_outstanding_transactions', to='rbx.transaction'),
        ),
    ]
