# Generated by Django 4.0.5 on 2024-03-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0038_recovery_outstanding_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adnr',
            name='is_btc',
            field=models.BooleanField(default=False),
        ),
    ]
