# Generated by Django 4.0.5 on 2024-03-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0039_adnr_is_btc'),
    ]

    operations = [
        migrations.AddField(
            model_name='adnr',
            name='btc_address',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
