# Generated by Django 4.0.5 on 2024-10-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0041_faucetwithdrawlrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FungibleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('ticker', models.CharField(max_length=64)),
                ('owner_address', models.CharField(max_length=64)),
                ('image_base64', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('decimal_places', models.IntegerField()),
                ('initial_supply', models.DecimalField(decimal_places=16, default=0.0, max_digits=32)),
                ('can_mint', models.BooleanField()),
                ('can_burn', models.BooleanField()),
                ('can_vote', models.BooleanField()),
                ('create_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.transaction')),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.nft')),
            ],
        ),
    ]
