# Generated by Django 4.0.5 on 2024-10-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0042_fungibletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Tx'), (1, 'Node'), (2, 'Nft Mint'), (3, 'Nft Tx'), (4, 'Nft Burn'), (5, 'Nft Sale'), (6, 'Address'), (7, 'Dst Registration'), (8, 'Vote Topic'), (9, 'Vote'), (10, 'Reserve'), (11, 'Sc Mint'), (12, 'Sc Tx'), (13, 'Sc Burn'), (14, 'Ftkn Mint'), (15, 'Ftkn Tx'), (16, 'Ftkn Burn'), (17, 'Tknz Mint'), (18, 'Tknz Tx'), (19, 'Tknz Burn')], verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='FungibleTokenTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mint', 'Mint'), ('burn', 'Burn'), ('transfer', 'Transfer')], max_length=16)),
                ('sc_identifier', models.CharField(max_length=64)),
                ('receiving_address', models.CharField(blank=True, max_length=64, null=True)),
                ('sending_address', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.fungibletoken')),
            ],
        ),
    ]
