# Generated by Django 4.0.5 on 2024-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0043_alter_transaction_type_fungibletokentx'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungibletoken',
            name='image_base64_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
