# Generated by Django 4.0.5 on 2024-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0044_fungibletoken_image_base64_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_fungible_token',
            field=models.BooleanField(default=False),
        ),
    ]
