# Generated by Django 4.0.5 on 2024-10-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0047_fungibletoken_banned_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVoteTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_identifier', models.CharField(max_length=64)),
                ('from_address', models.CharField(max_length=64)),
                ('topic_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('vote_requirement', models.DecimalField(decimal_places=16, max_digits=32)),
                ('created_at', models.DateTimeField()),
                ('voting_ends_at', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.fungibletoken')),
            ],
        ),
    ]
