# Generated by Django 4.0.5 on 2024-10-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0048_tokenvotetopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VbtcToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_identifier', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('owner_address', models.CharField(max_length=64)),
                ('image_base64', models.TextField()),
                ('image_base64_url', models.URLField(blank=True, null=True)),
                ('deposit_address', models.CharField(max_length=64)),
                ('public_key_proofs', models.TextField(blank=True)),
                ('global_balance', models.DecimalField(decimal_places=16, default=0.0, max_digits=32)),
                ('created_at', models.DateField()),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.nft')),
            ],
        ),
        migrations.CreateModel(
            name='VbtcTokenAmountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('created_at', models.DateField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.vbtctoken')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.transaction')),
            ],
        ),
    ]
