# Generated by Django 4.0.5 on 2024-10-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0049_vbtctoken_vbtctokenamounttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_vbtc',
            field=models.BooleanField(default=False),
        ),
    ]
