# Generated by Django 4.0.5 on 2024-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0050_nft_is_vbtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbtctoken',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
