# Generated by Django 4.0.5 on 2024-10-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0052_vbtctoken_total_recieved_vbtctoken_total_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbtctokenamounttransfer',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
