# Generated by Django 4.0.5 on 2024-10-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0053_alter_vbtctokenamounttransfer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVoteTopicVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('value', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.tokenvotetopic')),
            ],
        ),
    ]
