# Generated by Django 4.0.5 on 2025-01-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0054_tokenvotetopicvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faucetwithdrawlrequest',
            name='verification_code',
        ),
    ]
