# Generated by Django 4.0.5 on 2025-01-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0056_fungibletoken_original_owner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='total_transactions',
            field=models.IntegerField(default=0),
        ),
    ]
