# Generated by Django 4.0.5 on 2025-01-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0057_circulation_total_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungibletoken',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
