# Generated by Django 4.0.5 on 2025-03-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0058_fungibletoken_nsfw'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbtctokenamounttransfer',
            name='is_multi',
            field=models.BooleanField(default=False),
        ),
    ]
