# Generated by Django 4.0.5 on 2026-03-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0059_vbtctokenamounttransfer_is_multi'),
    ]

    operations = [
        migrations.CreateModel(
            name='VbtcV2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_identifier', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('owner_address', models.CharField(max_length=64)),
                ('image_base64', models.TextField()),
                ('image_base64_url', models.URLField(blank=True, null=True)),
                ('deposit_address', models.CharField(max_length=128)),
                ('frost_group_public_key', models.TextField(blank=True)),
                ('dkg_proof', models.TextField(blank=True)),
                ('validator_snapshot', models.JSONField(blank=True, null=True)),
                ('required_threshold', models.IntegerField(default=0)),
                ('proof_block_height', models.IntegerField(default=0)),
                ('global_balance', models.DecimalField(decimal_places=16, default=0.0, max_digits=32)),
                ('total_received', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('total_sent', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('tx_count', models.IntegerField(default=0)),
                ('is_pending_withdrawal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.nft')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Tx'), (1, 'Node'), (2, 'Nft Mint'), (3, 'Nft Tx'), (4, 'Nft Burn'), (5, 'Nft Sale'), (6, 'Address'), (7, 'Dst Registration'), (8, 'Vote Topic'), (9, 'Vote'), (10, 'Reserve'), (11, 'Sc Mint'), (12, 'Sc Tx'), (13, 'Sc Burn'), (14, 'Ftkn Mint'), (15, 'Ftkn Tx'), (16, 'Ftkn Burn'), (17, 'Tknz Mint'), (18, 'Tknz Tx'), (19, 'Tknz Burn'), (25, 'Vbtc V2 Mint'), (26, 'Vbtc V2 Transfer'), (27, 'Vbtc V2 Withdrawal Request'), (28, 'Vbtc V2 Withdrawal Complete')], verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='VbtcV2WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_address', models.CharField(max_length=64)),
                ('btc_address', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('fee_rate', models.DecimalField(decimal_places=8, max_digits=16)),
                ('btc_transaction_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed')], default='requested', max_length=16)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rbx.transaction')),
                ('request_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rbx.transaction')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='rbx.vbtcv2token')),
            ],
        ),
        migrations.CreateModel(
            name='VbtcV2TokenTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=64)),
                ('to_address', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('created_at', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.vbtcv2token')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbx.transaction')),
            ],
        ),
    ]
