# Generated by Django 4.0.5 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0060_vbtcv2token_alter_transaction_type_and_more'),
    ]

    operations = [
        # P0: Block.date_crafted - block sync queries filter on this
        migrations.AlterField(
            model_name='block',
            name='date_crafted',
            field=models.DateTimeField(db_index=True, verbose_name='Date Crafted'),
        ),
        # P0: Transaction.date_crafted - default ordering field for tx list API
        migrations.AlterField(
            model_name='transaction',
            name='date_crafted',
            field=models.DateTimeField(db_index=True, verbose_name='Date Crafted'),
        ),
        # P0: Transaction.type - filtered in 8+ queries
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Tx'), (1, 'Node'), (2, 'Nft Mint'), (3, 'Nft Tx'), (4, 'Nft Burn'), (5, 'Nft Sale'), (6, 'Address'), (7, 'Dst Registration'), (8, 'Vote Topic'), (9, 'Vote'), (10, 'Reserve'), (11, 'Sc Mint'), (12, 'Sc Tx'), (13, 'Sc Burn'), (14, 'Ftkn Mint'), (15, 'Ftkn Tx'), (16, 'Ftkn Burn'), (17, 'Tknz Mint'), (18, 'Tknz Tx'), (19, 'Tknz Burn'), (25, 'Vbtc V2 Mint'), (26, 'Vbtc V2 Transfer'), (27, 'Vbtc V2 Withdrawal Request'), (28, 'Vbtc V2 Withdrawal Complete')], db_index=True, verbose_name='Type'),
        ),
        # P1: Nft.owner_address - address NFT lookups
        migrations.AlterField(
            model_name='nft',
            name='owner_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P1: Nft.minter_address - NFT view filtering
        migrations.AlterField(
            model_name='nft',
            name='minter_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P1: MasterNode.is_active - active validator filtering
        migrations.AlterField(
            model_name='masternode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        # P1: MasterNode.date_connected - default ordering field
        migrations.AlterField(
            model_name='masternode',
            name='date_connected',
            field=models.DateTimeField(db_index=True, verbose_name='Date Connected'),
        ),
        # P1: Callback.from_address / to_address - balance calculations
        migrations.AlterField(
            model_name='callback',
            name='from_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='callback',
            name='to_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P1: Recovery.original_address / new_address - balance calculations
        migrations.AlterField(
            model_name='recovery',
            name='original_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='new_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P2: FungibleTokenTx.sending_address / receiving_address - balance calculations
        migrations.AlterField(
            model_name='fungibletokentx',
            name='sending_address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fungibletokentx',
            name='receiving_address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        # P2: VbtcToken.sc_identifier / owner_address
        migrations.AlterField(
            model_name='vbtctoken',
            name='sc_identifier',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vbtctoken',
            name='owner_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P2: VbtcTokenAmountTransfer.address
        migrations.AlterField(
            model_name='vbtctokenamounttransfer',
            name='address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P2: VbtcV2Token.sc_identifier / owner_address
        migrations.AlterField(
            model_name='vbtcv2token',
            name='sc_identifier',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vbtcv2token',
            name='owner_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P2: VbtcV2TokenTransfer.from_address / to_address
        migrations.AlterField(
            model_name='vbtcv2tokentransfer',
            name='from_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vbtcv2tokentransfer',
            name='to_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        # P2: VbtcV2WithdrawalRequest.requestor_address
        migrations.AlterField(
            model_name='vbtcv2withdrawalrequest',
            name='requestor_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
