# Generated by Django 4.0.5 on 2026-06-11 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0061_add_missing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbtcv2withdrawalrequest',
            name='cancel_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rbx.transaction'),
        ),
        migrations.AddField(
            model_name='vbtcv2withdrawalrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Tx'), (1, 'Node'), (2, 'Nft Mint'), (3, 'Nft Tx'), (4, 'Nft Burn'), (5, 'Nft Sale'), (6, 'Address'), (7, 'Dst Registration'), (8, 'Vote Topic'), (9, 'Vote'), (10, 'Reserve'), (11, 'Sc Mint'), (12, 'Sc Tx'), (13, 'Sc Burn'), (14, 'Ftkn Mint'), (15, 'Ftkn Tx'), (16, 'Ftkn Burn'), (17, 'Tknz Mint'), (18, 'Tknz Tx'), (19, 'Tknz Burn'), (20, 'Tknz Withdrawal Request'), (21, 'Tknz Withdrawal Complete'), (22, 'Validator Registration'), (23, 'Validator Heartbeat'), (25, 'Vbtc V2 Mint'), (26, 'Vbtc V2 Transfer'), (27, 'Vbtc V2 Withdrawal Request'), (28, 'Vbtc V2 Withdrawal Complete'), (29, 'Vbtc V2 Withdrawal Cancel'), (30, 'Vbtc V2 Withdrawal Vote'), (31, 'Vfx Shield'), (32, 'Vfx Unshield'), (33, 'Vfx Private Transfer'), (34, 'Vbtc Shield'), (35, 'Vbtc Unshield'), (36, 'Vbtc Private Transfer'), (37, 'Vbtc Bridge Lock'), (38, 'Vbtc Bridge Unlock')], db_index=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='vbtcv2withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=16),
        ),
    ]
