# Generated by Django 4.0.5 on 2026-06-11 18:21

from django.db import migrations, models
from django.db.models import Count, Min


def dedupe_transfers(apps, schema_editor):
    """Remove duplicate (token, transaction) transfer rows, keeping the
    oldest. Duplicates were created by reprocess_vbtc_v2 runs before
    get_or_create landed (commit 727978b) and double-count balances.
    Must run before the unique constraint below can be applied.
    """
    VbtcV2TokenTransfer = apps.get_model("rbx", "VbtcV2TokenTransfer")
    dups = (
        VbtcV2TokenTransfer.objects.values("token_id", "transaction_id")
        .annotate(n=Count("id"), keep=Min("id"))
        .filter(n__gt=1)
    )
    for dup in dups:
        VbtcV2TokenTransfer.objects.filter(
            token_id=dup["token_id"], transaction_id=dup["transaction_id"]
        ).exclude(id=dup["keep"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0062_vbtcv2withdrawalrequest_cancel_transaction_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_transfers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='vbtcv2tokentransfer',
            constraint=models.UniqueConstraint(fields=('token', 'transaction'), name='uniq_vbtcv2transfer_token_tx'),
        ),
    ]
