# Generated by Django 4.0.5 on 2026-07-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0063_vbtcv2tokentransfer_uniq_vbtcv2transfer_token_tx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnindexedMint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_identifier', models.CharField(db_index=True, max_length=64)),
                ('transaction_type', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unindexed_mints', to='rbx.transaction')),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'unique_together': {('sc_identifier', 'transaction')},
            },
        ),
    ]
