# Generated by Django 4.0.5 on 2026-08-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0064_unindexedmint'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbtcv2withdrawalrequest',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vbtcv2withdrawalrequest',
            name='signed_btc_tx_hex',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vbtcv2withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_btc', 'Pending BTC'), ('completed', 'Completed'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled')], default='requested', max_length=32),
        ),
    ]
