# Generated by Django 4.0.5 on 2026-09-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0066_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbtcv2tokentransfer',
            name='is_multi',
            field=models.BooleanField(default=False),
        ),
    ]
