# Generated by Django 4.0.5 on 2023-05-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0026_remove_bid_completion_has_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('is_third_party', models.BooleanField()),
                ('buyer_address', models.CharField(max_length=60)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='shop.shop')),
            ],
            options={
                'unique_together': {('shop', 'buyer_address')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('is_from_buyer', models.BooleanField()),
                ('body', models.TextField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='connect.chatthread')),
            ],
        ),
    ]
