# Generated by Django 4.0.5 on 2023-05-04 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_chatthread_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('67798233-9e49-4eb4-8df2-6cf4bedb0478'), unique=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('63e3ed19-a8b8-4c10-b59b-69edc43d6d78'), unique=True),
        ),
    ]
