# Generated by Django 4.0.5 on 2023-05-04 20:27

import connect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_chatmessage_uuid_chatthread_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='uuid',
            field=models.UUIDField(db_index=True, default=connect.models.get_uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='uuid',
            field=models.UUIDField(db_index=True, default=connect.models.get_uuid, editable=False, unique=True),
        ),
    ]
