# Generated by Django 4.0.5 on 2023-03-29 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbx', '0024_alter_address_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('unique_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner_address', models.CharField(max_length=60)),
                ('is_offline', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('smart_contract_uid', models.CharField(max_length=64)),
                ('owner_address', models.CharField(max_length=60)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('floor_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_visible_before_start_date', models.BooleanField()),
                ('is_visible_after_end_date', models.BooleanField()),
                ('final_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('winning_address', models.CharField(blank=True, max_length=60, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='shop.collection')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='rbx.nft')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='shop.shop'),
        ),
    ]
