# Generated by Django 4.0.5 on 2023-03-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='listing',
            new_name='shop',
        ),
    ]
