# Generated by Django 4.0.5 on 2023-03-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_listing_collection_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
