# Generated by Django 4.0.5 on 2023-03-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_listing_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='thumbnail_url',
        ),
    ]
