# Generated by Django 4.0.5 on 2023-03-30 01:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_listing_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='thumbnails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
