# Generated by Django 4.0.5 on 2023-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_listing_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='thumbnails_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
