# Generated by Django 4.0.5 on 2023-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_listing_thumbnails_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_third_party',
            field=models.BooleanField(default=False),
        ),
    ]
