# Generated by Django 4.0.5 on 2023-04-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_is_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
