# Generated by Django 4.0.5 on 2023-04-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbx', '0025_circulation_total_addresses'),
        ('shop', '0008_collection_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='rbx.nft'),
        ),
    ]
