# Generated by Django 4.0.5 on 2023-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_listing_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
