# Generated by Django 4.0.5 on 2023-04-24 12:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_collection_is_deleted_listing_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='thumbnails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
