# Generated by Django 4.0.5 on 2023-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_listing_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_sale_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='purchase_key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
    ]
