# Generated by Django 4.0.5 on 2023-04-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_listing_is_cancelled_listing_is_sale_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='thumbnails_fetched',
        ),
    ]
