# Generated by Django 4.0.5 on 2023-04-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_listing_thumbnails_fetched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=60)),
                ('signature', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('send_time', models.IntegerField()),
                ('is_buy_now', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('purchase_key', models.CharField(blank=True, max_length=60, null=True)),
                ('bid_status', models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'Sent'), (3, 'Received')], default=2)),
                ('send_receive', models.IntegerField(choices=[(0, 'Send'), (1, 'Received')], default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='shop.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.IntegerField()),
                ('current_bid_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('increment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_reserve_met', models.BooleanField(default=False)),
                ('is_auction_over', models.BooleanField(default=False)),
                ('current_winning_address', models.CharField(blank=True, max_length=60, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='shop.listing')),
            ],
        ),
    ]
