# Generated by Django 4.0.5 on 2023-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_bid_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='auction',
            name='increment_amount',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
            preserve_default=False,
        ),
    ]
