# Generated by Django 4.0.5 on 2023-04-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_bid_status_bid_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_reserve_met',
        ),
    ]
