# Generated by Django 4.0.5 on 2023-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_auction_is_reserve_met'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
