# Generated by Django 4.0.5 on 2023-04-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_shop_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='increment_amount',
        ),
    ]
