# Generated by Django 4.0.5 on 2023-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_collection_options_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_crawled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
