# Generated by Django 4.0.5 on 2023-05-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_shop_last_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='offline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
