# Generated by Django 4.0.5 on 2023-05-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_shop_offline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ip_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
