# Generated by Django 4.0.5 on 2023-05-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_shop_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_third_party',
            field=models.BooleanField(default=False),
        ),
    ]
