# Generated by Django 4.0.5 on 2023-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_bid_is_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='pre_signed_sale_complete_tx',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
