# Generated by Django 4.0.5 on 2023-05-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_bid_pre_signed_sale_complete_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='pre_signed_sale_complete_tx',
            field=models.TextField(blank=True, null=True),
        ),
    ]
