# Generated by Django 4.0.5 on 2023-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_bid_pre_signed_sale_complete_tx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='completion_has_processed',
            field=models.BooleanField(default=False),
        ),
    ]
