# Generated by Django 4.0.5 on 2023-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_bid_completion_has_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='completion_has_processed',
        ),
        migrations.AddField(
            model_name='listing',
            name='completion_has_processed',
            field=models.BooleanField(default=False),
        ),
    ]
