# Generated by Django 4.0.5 on 2023-05-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_bid_completion_has_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_offline',
        ),
    ]
