# Generated by Django 4.0.5 on 2023-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_listing_is_sale_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ignore_import',
            field=models.BooleanField(default=False),
        ),
    ]
