# Generated by Django 4.0.5 on 2022-06-22 18:09

import django.core.validators
from django.db import migrations, models

import project.fields
import project.utils.time
import project.utils.uuid
import project.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=project.utils.uuid.get_uuid,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        validators=[project.validators.TypeValidator(dict)],
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=project.utils.time.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "email",
                    project.fields.CICharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        validators=[
                            project.validators.TypeValidator(str),
                            django.core.validators.MaxLengthValidator(128),
                            django.core.validators.EmailValidator(),
                        ],
                        verbose_name="Email",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_admin", models.BooleanField(default=False, verbose_name="Admin")),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
