# Generated by Django 4.0.5 on 2023-04-09 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_user_options_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('token', models.TextField()),
                ('message', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 19, 12, 20, 865493, tzinfo=utc))),
            ],
        ),
    ]
