# Generated by Django 4.0.5 on 2023-04-09 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 19, 14, 11, 555219, tzinfo=utc)),
        ),
    ]
