# Generated by Django 4.0.5 on 2023-04-09 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_authtoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='signature',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 19, 19, 59, 123670, tzinfo=utc)),
        ),
    ]
