# Generated by Django 4.0.5 on 2023-04-09 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_authtoken_signature_alter_authtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 21, 43, 28, 875625, tzinfo=utc)),
        ),
    ]
