# Generated by Django 4.0.5 on 2023-04-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_alter_authtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
