# Generated by Django 4.0.5 on 2023-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_alter_authtoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('address', 'email')},
            },
        ),
    ]
